server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:${AUTH_SERVICE_URI:lb://auth-service}}
          predicates:
            - Path=/api/v1/auth/**

        - id: customer-service
          uri: ${CUSTOMER_SERVICE_URL:${CUSTOMER_SERVICE_URI:lb://customer-service}}
          predicates:
            - Path=/api/v1/customers/**,/api/v1/vehicles/**

        - id: provider-service
          uri: ${PROVIDER_SERVICE_URL:${PROVIDER_SERVICE_URI:lb://provider-service}}
          predicates:
            - Path=/api/v1/providers/**

        - id: booking-service
          uri: ${BOOKING_SERVICE_URL:${BOOKING_SERVICE_URI:lb://booking-service}}
          predicates:
            - Path=/api/v1/bookings/**,/api/v1/provider/bookings/**

        - id: matching-service
          uri: ${MATCHING_SERVICE_URL:${MATCHING_SERVICE_URI:lb://matching-service}}
          predicates:
            - Path=/api/v1/matching/**,/api/v1/providers/nearby/**

        - id: tracking-service-ws
          uri: ${TRACKING_SERVICE_WS_URL:${TRACKING_SERVICE_WS_URI:lb:ws://tracking-service}}
          predicates:
            - Path=/ws/**

        - id: tracking-service
          uri: ${TRACKING_SERVICE_URL:${TRACKING_SERVICE_URI:lb://tracking-service}}
          predicates:
            - Path=/api/v1/tracking/**

        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:${PAYMENT_SERVICE_URI:lb://payment-service}}
          predicates:
            - Path=/api/v1/invoices/**,/api/v1/payments/**

        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:${NOTIFICATION_SERVICE_URI:lb://notification-service}}
          predicates:
            - Path=/api/v1/notifications/**

        - id: rating-service
          uri: ${RATING_SERVICE_URL:${RATING_SERVICE_URI:lb://rating-service}}
          predicates:
            - Path=/api/v1/ratings/**
